In [9]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
print("Orijinal notlar listesi:", notlar)
benzersiz_sirali = []
for not_degeri in notlar:
    if not_degeri not in benzersiz_sirali:
        benzersiz_sirali.append(not_degeri)
print("Sıralaması korunmuş benzersiz notlar:", benzersiz_sirali)
en_yuksek = max(notlar)
en_dusuk = min(notlar)
print(f"En yüksek not: {en_yuksek}")
print(f"En düşük not: {en_dusuk}")
sirali_notlar = sorted(notlar)
print("Sıralı notlar:", sirali_notlar)

Orijinal notlar listesi: [85, 92, 76, 92, 100, 76, 85, 92]
Sıralaması korunmuş benzersiz notlar: [85, 92, 76, 100]
En yüksek not: 100
En düşük not: 76
Sıralı notlar: [76, 76, 85, 85, 92, 92, 92, 100]


In [6]:
def armstrong_kontrolu(sayi):
    sayi_str = str(sayi)
    basamak_sayisi = len(sayi_str)
    toplam = 0
    for basamak in sayi_str:
        toplam += int(basamak) ** basamak_sayisi
    return toplam == sayi

kullanici_sayi = int(input("Bir sayı girin: "))
if armstrong_kontrolu(kullanici_sayi):
    print(f"{kullanici_sayi} bir Armstrong sayısıdır!")
else:
    print(f"{kullanici_sayi} bir Armstrong sayısı değildir.")

Bir sayı girin:  153


153 bir Armstrong sayısıdır!


In [12]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
print("Küme A:", A)
print("Küme B:", B)
ortak_diller = A & B
print("Ortak diller:", ortak_diller)
sadece_A = A - B
print("Sadece A'da olan diller:", sadece_A)
birlesim_alfabetik = sorted(A | B)
print("Birleşim (alfabetik):", birlesim_alfabetik)

Küme A: {'R', 'Python', 'Java', 'SQL'}
Küme B: {'C++', 'SQL', 'JavaScript', 'Python'}
Ortak diller: {'SQL', 'Python'}
Sadece A'da olan diller: {'R', 'Java'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [1]:
import random
import statistics
rastgele_sayilar = [random.randint(1, 100) for _ in range(10)]
print("Rastgele sayılar:", rastgele_sayilar)
ortalama = statistics.mean(rastgele_sayilar)
standart_sapma = statistics.stdev(rastgele_sayilar)
print("Ortalama:", ortalama)
print("Standart sapma:", standart_sapma)

Rastgele sayılar: [6, 93, 66, 16, 44, 17, 24, 90, 17, 92]
Ortalama: 46.5
Standart sapma: 35.47847547770651


In [13]:
from collections import Counter

def kelime_sayaci(metin):
    kelimeler = metin.split()    
    toplam_kelime = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sik = Counter(kelimeler).most_common(1)[0][0]    
    return toplam_kelime, en_uzun, en_sik
test_metin = "Python veri bilimi için harika bir dil Python kolay ve güçlü Python"
toplam, uzun, sik = kelime_sayaci(test_metin)
print("Test metni:", test_metin)
print("Toplam kelime sayısı:", toplam)
print("En uzun kelime:", uzun)
print("En sık geçen kelime:", sik)

Test metni: Python veri bilimi için harika bir dil Python kolay ve güçlü Python
Toplam kelime sayısı: 12
En uzun kelime: Python
En sık geçen kelime: Python


In [2]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
print("Orijinal sayılar:", sayilar)
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print("Çift sayılar:", cift_sayilar)
kareler = list(map(lambda x: x**2, cift_sayilar))
print("Kareleri:", kareler)
azalan_kareler = sorted(kareler, reverse=True)
print("Azalan sırada kareler:", azalan_kareler)

Orijinal sayılar: [5, 12, 7, 18, 24, 3, 16]
Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Azalan sırada kareler: [576, 324, 256, 144]


In [3]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
print("Orijinal kelimeler:", kelimeler)
uzunluga_gore_sirali = sorted(kelimeler, key=lambda x: len(x))
print("Uzunluğa göre sıralı:", uzunluga_gore_sirali)

Orijinal kelimeler: ['veri', 'bilim', 'analiz', 'yapayzeka', 'python']
Uzunluğa göre sıralı: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [11]:
def rakam_toplami(metin):
    import re
    sayilar = re.findall(r'\d+', metin)
    return sum(int(sayi) for sayi in sayilar), sayilar
test_string = "abc12def3"
toplam, bulunan_sayilar = rakam_toplami(test_string)
print("Test string:", test_string)
print("Bulunan sayılar:", bulunan_sayilar)
print("Sayıların toplamı:", " + ".join(bulunan_sayilar), "=", toplam)

Test string: abc12def3
Bulunan sayılar: ['12', '3']
Sayıların toplamı: 12 + 3 = 15


In [ ]:
import numpy as np
dizi = np.random.randint(0, 51, 10)
print("Numpy dizisi:", dizi)
ortalama = np.mean(dizi)
standart_sapma = np.std(dizi)
en_buyuk = np.max(dizi)
print("Ortalama:", ortalama)
print("Standart sapma:", standart_sapma)
print("En büyük değer:", en_buyuk)

In [12]:
import numpy as np
matris = np.random.rand(5, 5)
print("5x5 Rastgele matris:")
print(matris)
sutun_ortalamalari = np.mean(matris, axis=0)
print("Her sütunun ortalaması:", sutun_ortalamalari)
binary_matris = (matris > 0.5).astype(int)
print("Binary matris:")
print(binary_matris)

5x5 Rastgele matris:
[[0.4543664  0.78150996 0.77460755 0.46401939 0.90317248]
 [0.20200151 0.14045397 0.63952733 0.45682678 0.87393732]
 [0.2326182  0.81923116 0.04505768 0.48987758 0.23481349]
 [0.33782609 0.1753433  0.01054773 0.10706605 0.96823474]
 [0.56330124 0.32612228 0.01948755 0.40578199 0.74796632]]
Her sütunun ortalaması: [0.35802269 0.44853213 0.29784557 0.38471436 0.74562487]
Binary matris:
[[0 1 1 0 1]
 [0 0 1 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 1]]
